version: "3.8"

services:
  python_app:
    build:
      dockerfile: Dockerfile
    command: python3 main.py
    depends_on:
      - db
    env_file:
      - .env_example

  db:
    image: postgres:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    expose:
      - 5432