version: "3.8"

services:
  db:
    image: postgres:latest
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

  python_app:
    build:
      dockerfile: Dockerfile
    command: python3 main.py
    depends_on:
      - db
    env_file:
      - .env_example